name: testing
on:
  workflow_dispatch:
run-name: running tests for searchenginepy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: Install dependencies
        uses: py-actions/py-dependency-install@v4
        with:
              path: "THEGAME/requirements.txt"
          
      - name: run tests # run main.py
        working-directory: THEGAME
        run: python thegame,py
